### ISSUE TITLE
添加筛选现货

### ISSUE THREAD

**Issue by Dachtire** [xiaowine/szlcsc-help#1]
部分品牌的整个类目均无现货，可以直接筛选排除掉，减少干扰。

**Comment by xiaowine** [comment]
> 部分品牌的整个类目均无现货，可以直接筛选排除掉，减少干扰。

能给一个品牌吗

**Comment by Dachtire** [comment]
> > 部分品牌的整个类目均无现货，可以直接筛选排除掉，减少干扰。
> 
> 能给一个品牌吗

UNITED(怡德)
